# Generated by Django 5.2 on 2025-05-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
